# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrderingService

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/microgrid.org/msp

    - &House01
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: House01MSP

        # ID to load the MSP definition as
        ID: House01MSP

        MSPDir: crypto-config/peerOrganizations/house01.microgrid.org/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.house01.microgrid.org
              Port: 7051

    - &House02
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: House02MSP

        # ID to load the MSP definition as
        ID: House02MSP

        MSPDir: crypto-config/peerOrganizations/house02.microgrid.org/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.house02.microgrid.org
              Port: 7051

    - &House03
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: House03MSP

        # ID to load the MSP definition as
        ID: House03MSP

        MSPDir: crypto-config/peerOrganizations/house03.microgrid.org/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.house03.microgrid.org
              Port: 7051

    - &House04
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: House04MSP

        # ID to load the MSP definition as
        ID: House04MSP

        MSPDir: crypto-config/peerOrganizations/house04.microgrid.org/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.house04.microgrid.org
              Port: 7051

    - &House05
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: House05MSP

        # ID to load the MSP definition as
        ID: House05MSP

        MSPDir: crypto-config/peerOrganizations/house05.microgrid.org/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.house05.microgrid.org
              Port: 7051

    - &House06
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: House06MSP

        # ID to load the MSP definition as
        ID: House06MSP

        MSPDir: crypto-config/peerOrganizations/house06.microgrid.org/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.house06.microgrid.org
              Port: 7051


################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.microgrid.org:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            MicroGridConsortium:
                Organizations:
                    - *House01
                    - *House02
                    - *House03
                    - *House04
                    - *House05
                    - *House06
    hachannel:
        Consortium: MicroGridConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *House01
                - *House02
                - *House03
                - *House04
                - *House05
                - *House06
