# Simple crypto-config.yaml, setting up 6 houses and 1 order.
# Assuming the domain is microgrid.org
# See example from:
# https://dev.to/damcosset/your-first-hyperledger-fabric-network-2n67

OrdererOrgs:
  - Name: OrderingService
    Domain: microgrid.org
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: House01
    Domain: house01.microgrid.org
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: House02
    Domain: house02.microgrid.org
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: House03
    Domain: house03.microgrid.org
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: House04
    Domain: house04.microgrid.org
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: House05
    Domain: house05.microgrid.org
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: House06
    Domain: house06.microgrid.org
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
